import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { hivePaths, normaliseUserPath } from "../../core/paths.ts";
import type { Command, CommandContext } from "../command-router.ts";

interface InitOptions {
  name: string;
  path: string;
  backend: "native" | "tmux" | "auto";
  template: string | undefined;
  acknowledgeDangerous: boolean;
}

function parseInitArgs(argv: string[]): InitOptions {
  const { values, positionals } = parseArgs({
    args: argv,
    options: {
      path: { type: "string" },
      backend: { type: "string" },
      template: { type: "string" },
      "acknowledge-dangerous": { type: "boolean" },
    },
    strict: true,
    allowPositionals: true,
  });
  const name = positionals[0];
  if (!name) {
    throw new Error("hive init <name> — name is required");
  }
  const backendStr = (values["backend"] as string | undefined) ?? "auto";
  if (!["native", "tmux", "auto"].includes(backendStr)) {
    throw new Error(`invalid --backend: ${backendStr} (must be native|tmux|auto)`);
  }
  const pathStr = (values["path"] as string | undefined) ?? process.cwd();
  return {
    name,
    path: normaliseUserPath(pathStr),
    backend: backendStr as "native" | "tmux" | "auto",
    template: values["template"] as string | undefined,
    acknowledgeDangerous: values["acknowledge-dangerous"] === true,
  };
}

async function handle(ctx: CommandContext): Promise<number> {
  let opts: InitOptions;
  try {
    opts = parseInitArgs(ctx.commandArgv);
  } catch (err) {
    ctx.logger.error(err instanceof Error ? err.message : String(err));
    return 2;
  }

  const root = join(opts.path, opts.name);
  if (existsSync(root)) {
    ctx.logger.error(`directory already exists: ${root}`);
    ctx.logger.info(
      "Refusing to scaffold over existing files. Move it aside or pick another name.",
    );
    return 1;
  }

  if (opts.template) {
    ctx.logger.warn(
      `--template ${opts.template} ignored: templates ship in checkpoint B+ once template content lands.`,
    );
  }

  printDangerousExplainer(ctx);
  if (!opts.acknowledgeDangerous) {
    ctx.logger.info("");
    ctx.logger.info("Pass --acknowledge-dangerous to confirm and scaffold:");
    ctx.logger.info(`  hive init ${opts.name} --acknowledge-dangerous`);
    return 1;
  }

  const paths = hivePaths(root);
  await mkdir(paths.root, { recursive: true });
  await mkdir(paths.personasDir, { recursive: true });
  await mkdir(paths.briefsDir, { recursive: true });
  await mkdir(paths.reportsDir, { recursive: true });

  // Default hive: chief + 2 workers as a starting point. The real template content lands
  // in the dev-swarm template brief; this init produces a valid minimum hive so the
  // customer can immediately run `hive up`.
  const personas = [
    {
      address: "chief-001",
      role: "chief",
      workspace: "chief-001",
      identityDoc: "personas/chief.md",
    },
    {
      address: "worker-001",
      role: "worker",
      workspace: "worker-001",
      identityDoc: "personas/worker.md",
    },
    {
      address: "worker-002",
      role: "worker",
      workspace: "worker-002",
      identityDoc: "personas/worker.md",
    },
  ];

  for (const p of personas) {
    await mkdir(join(root, p.workspace), { recursive: true });
  }

  const chiefIdentity = `---
address: chief-001
role: chief
model_preference: claude-opus-4-7
---

# Chief

You are the Chief of this hive. The King (the human running the hive) addresses you
first. Decompose briefs into worker-sized tasks and dispatch them. Synthesize results.
`;

  const workerIdentity = `---
role: worker
model_preference: claude-opus-4-6
---

# Worker

You are a worker in this hive. Execute the briefs you receive from the Chief. Write
clear reports. Ask for clarification when blocked.
`;

  await writeFile(join(paths.personasDir, "chief.md"), chiefIdentity);
  await writeFile(join(paths.personasDir, "worker.md"), workerIdentity);

  const tomlContent = `[hive]
name = "${opts.name}"
description = "Generated by \`hive init ${opts.name}\`"
workspace_root = "."

[topology]
shape = "hub-spoke"
human_dispatch = "any"

[runtime]
backend = "${opts.backend}"
default_model = "claude-opus-4-7"
acknowledged_dangerous = true

[runtime.native]
target_window_size_px = [480, 320]
overlay_opacity = 0.5
overlay_focus_opacity = 0.95
use_blur = true

${personas
  .map(
    (p, i) =>
      `[[personas]]
address = "${p.address}"
role = "${p.role}"
identity_doc = "${p.identityDoc}"
workspace = "./${p.workspace}"
${
  i === 0
    ? `manages = [${personas
        .slice(1)
        .map((c) => `"${c.address}"`)
        .join(", ")}]`
    : `reports_to = "chief-001"`
}
`,
  )
  .join("\n")}
`;

  await writeFile(paths.hiveToml, tomlContent);

  ctx.logger.print(`hive scaffolded at ${root}`);
  ctx.logger.print("next steps:");
  ctx.logger.print(`  cd ${root}`);
  ctx.logger.print("  hive up");
  ctx.logger.print("  hive status --tree");
  return 0;
}

function printDangerousExplainer(ctx: CommandContext): void {
  ctx.logger.print("apicultr spawns Claude Code with `--dangerously-skip-permissions` for every");
  ctx.logger.print("persona. Workers will read, write, and execute files inside their workspaces");
  ctx.logger.print("without per-tool approval prompts. This is the only way the swarm runtime");
  ctx.logger.print("works at hive scale, and it is the customer's choice to opt in.");
  ctx.logger.print("");
  ctx.logger.print("Mitigations:");
  ctx.logger.print("  • Each persona's workspace is isolated to its own directory.");
  ctx.logger.print("  • The hive.toml's `acknowledged_dangerous = true` flag will be set.");
  ctx.logger.print("  • You can `hive down` at any time to terminate all workers.");
}

export const initCommand: Command = {
  name: "init",
  summary: "Scaffold a new hive",
  usage: "hive init <name> [--path <dir>] [--backend native|tmux|auto] [--acknowledge-dangerous]",
  description:
    "Creates <name>/ with hive.toml, personas/, workspace dirs, and .hive/. Requires explicit acknowledgement of --dangerously-skip-permissions semantics.",
  handler: handle,
};
